# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Stat 2
tagline:          'UCB - Stat 2'
description:      'Introduction to Statistics'
url:              http://gastonsanchez.com/stat2
baseurl:          stat2

author:
  name:           'Gaston Sanchez'
  url:            http://gastonsanchez.com

paginate:         5

# Custom vars
version:          Spring 2016

github:
  repo:           https://github.com/gastonstat/stat2
